tw/updated readme
UTDallasEPICS/Warren-Automated-Onboard pull request #37
Opened 2023-09-24 03:43 UTC by TusharW4ni

Revamped the readme file to look like Taz's example. Added Project Setup section. Kept the stuff from the previous semester but commented it out. In the first commit to this branch, I had tried to style the toggles to look like H3. It worked in VS Code however in github it didn't render out properly so in the subsequent commit I just took that part out.

2023-09-24 03:44 UTC, TusharW4ni commented
Please let me know, if you want any changes.
Thank you.

2023-09-24 05:19 UTC, MStolen requested changes
I would just like to see the big comment at the top removed and this will be a great update.

2023-09-24 05:19 UTC, MStolen commented on README.md
> +<!---# Getting Started with Create React App
You can just remove this. It will all be saved in the version history, so there is no reason to keep it.

2023-09-25 14:03 UTC, TusharW4ni commented
Alright, removed the commented text 👍.

2023-09-27 05:39 UTC, MStolen approved these changes

2023-09-27 05:39 UTC, merged